[project]
name = "bicycle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "openai>=1.101.0",
    "pandas>=2.3.2",
    "psycopg[binary]>=3.2.9",
    "sqlalchemy>=2.0.43",
]
